ALTER TABLE `dbo_sms_inbox` 
ADD COLUMN `is_processed` SMALLINT(6) NOT NULL DEFAULT '0' AFTER `is_read`;

INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (46, 'Workflow', 'tcg_wf_workflows', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (47, 'Workflow Steps', 'tcg_wf_steps', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (48, 'Workflow Steps Actions', 'tcg_wf_steps_actions', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (49, 'Workflow Transitions', 'tcg_wf_transitions', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (50, 'Workflow Transitions Actions', 'tcg_wf_transitions_actions', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (51, 'Workflow User Groups', 'tcg_wf_user_groups', 'id', 'name');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (52, 'Workflow Instances', 'tcg_wf_instances', 'id', 'entity');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (53, 'Workflow Instances Steps', 'tcg_wf_instances_steps', 'id', 'step');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`) VALUES (54, 'Workflow Instances Actions', 'tcg_wf_instances_actions', 'id', 'action');
UPDATE `dbo_crud_tables` SET `name` = 'Master Kode Wilayah' WHERE (`id` = '26');
UPDATE `dbo_crud_tables` SET `name` = 'Audit Trails' WHERE (`id` = '24');

ALTER TABLE `dbo_wf_workflows` 
ADD COLUMN `entity_id` INT(11) NULL DEFAULT NULL AFTER `entity`;

INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `order_no`, `visible`, `label`, `column_type`, `data_priority`, `foreign_key`, `reference_soft_delete`, `allow_insert`, `allow_edit`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_bubble`, `allow_filter`, `filter_label`, `filter_css`, `created_on`, `updated_on`, `is_deleted`) VALUES (NULL, '45', 'id', '1', '1', 'Id', 'tcg_readonly', '1', '0', '1', '0', '1', '', 'tcg_readonly', '', '0', '0', '0', '', '', '2021-03-17 20:17:56', '2021-03-17 20:17:56', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '45', 'label', '', '3', '1', 'Label', '', 'tcg_text', '3', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '45', 'nama', '', '2', '1', 'Nama', '', 'tcg_text', '2', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');

INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `order_no`, `visible`, `label`, `column_type`, `data_priority`, `foreign_key`, `reference_soft_delete`, `allow_insert`, `allow_edit`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_bubble`, `allow_filter`, `filter_label`, `filter_css`, `created_on`, `updated_on`, `is_deleted`) VALUES (NULL, '46', 'id', '1', '1', 'Id', 'tcg_readonly', '1', '0', '1', '0', '1', '', 'tcg_readonly', '', '0', '0', '0', '', '', '2021-03-17 20:17:56', '2021-03-17 20:17:56', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '46', 'label', '', '3', '1', 'Label', '', 'tcg_text', '3', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '46', 'name', '', '2', '1', 'Nama', '', 'tcg_text', '2', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'description', '', '3', '1', 'Deskripsi', '', 'tcg_text', '10', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'data_model', '', '2', '1', 'Data Model', '', 'tcg_text', '11', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'entity', '', '3', '1', 'Entity', '', 'tcg_text', '12', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'entity_id', '', '2', '1', 'Entity Id', '', 'tcg_text', '13', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'params', '', '3', '1', 'Parameter', '', 'tcg_text', '14', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'role_id', '', '2', '1', 'Peran', '', 'tcg_text', '15', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '1');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('46', 'user_group', '', '2', '1', 'Grup Pengguna', '', 'tcg_text', '16', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');

UPDATE `dbo_crud_columns` SET `is_deleted` = '0' WHERE (`id` = '270');

UPDATE `dbo_crud_columns` SET `order_no` = '4' WHERE (`id` = '385');
UPDATE `dbo_crud_columns` SET `order_no` = '5' WHERE (`id` = '386');
UPDATE `dbo_crud_columns` SET `order_no` = '6' WHERE (`id` = '387');
UPDATE `dbo_crud_columns` SET `order_no` = '7' WHERE (`id` = '388');
UPDATE `dbo_crud_columns` SET `order_no` = '8' WHERE (`id` = '389');
UPDATE `dbo_crud_columns` SET `order_no` = '9' WHERE (`id` = '390');
UPDATE `dbo_crud_columns` SET `order_no` = '10' WHERE (`id` = '391');

INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `order_no`, `visible`, `label`, `column_type`, `data_priority`, `foreign_key`, `reference_soft_delete`, `allow_insert`, `allow_edit`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_bubble`, `allow_filter`, `filter_label`, `filter_css`, `created_on`, `updated_on`, `is_deleted`) VALUES (NULL, '47', 'id', '1', '1', 'Id', 'tcg_readonly', '1', '0', '1', '0', '1', '', 'tcg_readonly', '', '0', '0', '0', '', '', '2021-03-17 20:17:56', '2021-03-17 20:17:56', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'name', '', '2', '1', 'Nama', '', 'tcg_text', '2', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'label', '', '3', '1', 'Label', '', 'tcg_text', '3', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_table_name`, `reference_key_column`, `reference_lookup_column`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'workflow_id', '', '4', '1', 'Workflow', '', 'tcg_select2', '4', '', '', '1', 'tcg_wf_workflows', 'id', 'name', '1', '', '1', '1', '', '', 'tcg_select2', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'prerequisites', '', '5', '1', 'Prerequisites', '', 'tcg_text', '5', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'is_final', '', '6', '1', 'Final', '', 'tcg_text', '6', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'role_id', '', '7', '1', 'Peran', '', 'tcg_text', '7', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '1');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '47', 'user_group', '', '8', '1', 'Grup Pengguna', '', 'tcg_text', '8', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');

INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `order_no`, `visible`, `label`, `column_type`, `data_priority`, `foreign_key`, `reference_soft_delete`, `allow_insert`, `allow_edit`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_bubble`, `allow_filter`, `filter_label`, `filter_css`, `created_on`, `updated_on`, `is_deleted`) VALUES (NULL, '48', 'id', '1', '1', 'Id', 'tcg_readonly', '1', '0', '1', '0', '1', '', 'tcg_readonly', '', '0', '0', '0', '', '', '2021-03-17 20:17:56', '2021-03-17 20:17:56', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'name', '', '2', '1', 'Nama', '', 'tcg_text', '2', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'action', '', '3', '1', 'Tindakan', '', 'tcg_text', '3', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_table_name`, `reference_key_column`, `reference_lookup_column`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'workflow_id', '', '4', '1', 'Workflow', '', 'tcg_select2', '4', '', '', '1', 'tcg_wf_workflows', 'id', 'name', '1', '', '1', '1', '', '', 'tcg_select2', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'step', '', '5', '1', 'Langkah', '', 'tcg_text', '5', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'type', '', '6', '1', 'Tipe Tindakan', '', 'tcg_text', '6', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'interval', '', '7', '1', 'Interval', '', 'tcg_text', '7', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'interval_type', '', '8', '1', 'Tipe Interval', '', 'tcg_text', '8', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'repeat', '', '9', '1', 'Pengulangan', '', 'tcg_text', '9', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '1');
INSERT INTO `dbo_crud_columns` (`id`, `table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '48', 'state_condition', '', '10', '1', 'Prasyarat Kondisi', '', 'tcg_text', '11', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'payload_condition', '', '11', '1', 'Prasyarat Payload', '', 'tcg_text', '12', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'transform_state', '', '12', '1', 'Ubah Kondisi', '', 'tcg_text', '13', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'transform_payload', '', '13', '1', 'Ubah Payload', '', 'tcg_text', '14', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'recipients', '', '14', '1', 'Penerima', '', 'tcg_text', '15', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'user_messages', '', '15', '1', 'Pesan', '', 'tcg_text', '16', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:35', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'user_action', '', '16', '1', 'Tindakan Pengguna', '', 'tcg_toggle', '17', '', '', '0', '1', '', '1', '1', '', '', 'tcg_toggle', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '1');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'editable_payload', '', '17', '1', 'Payload Yang Bisa Diubah', '', 'tcg_text', '18', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');
INSERT INTO `dbo_crud_columns` (`table_id`, `name`, `column_name`, `order_no`, `visible`, `label`, `css`, `column_type`, `data_priority`, `options_array`, `options_data_model`, `foreign_key`, `reference_soft_delete`, `reference_where_clause`, `allow_insert`, `allow_edit`, `edit_field`, `edit_label`, `edit_type`, `edit_css`, `edit_compulsory`, `edit_info`, `edit_attr_array`, `edit_bubble`, `edit_onchange_js`, `edit_options_array`, `allow_filter`, `filter_label`, `filter_type`, `filter_css`, `filter_attr_array`, `filter_onchange_js`, `filter_options_array`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('48', 'order_no', '', '18', '1', 'Urutan', '', 'tcg_text', '19', '', '', '0', '1', '', '1', '1', '', '', 'tcg_text', '', '1', '', '', '0', '', '', '0', '', '', '', '', '', '', '2021-03-17 20:17:56', '2021-03-21 19:48:19', '990', '0');

UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_workflows' WHERE (`id` = '46');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_steps' WHERE (`id` = '47');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_steps_actions' WHERE (`id` = '48');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_transitions' WHERE (`id` = '49');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_transitions_actions' WHERE (`id` = '50');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_user_groups' WHERE (`id` = '51');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_instances' WHERE (`id` = '52');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_instances_steps' WHERE (`id` = '53');
UPDATE `dbo_crud_tables` SET `table_name` = 'dbo_wf_instances_actions' WHERE (`id` = '54');

UPDATE `dbo_crud_columns` SET `reference_table_name` = 'dbo_wf_workflows' WHERE (`id` = '395');
UPDATE `dbo_crud_columns` SET `reference_table_name` = 'dbo_wf_workflows' WHERE (`id` = '439');

UPDATE `dbo_crud_columns` SET `data_priority` = '-1' WHERE (`id` = '106');

UPDATE `dbo_crud_pages` SET `page_footer` = '<script type=\"text/javascript\">\n     function view_edit_column(e, dt, node, conf) {\n         alert (\'Kolom Editor: \' + JSON.stringify(conf));\n \n         //dt.hide(undefined,false)\n     }\n \n     function view_filter_column(e, dt, node, conf) {\n         alert (\'Kolom Filter: \' + JSON.stringify(conf));\n     }\n \n     function view_fkey_column(e, dt, node, conf) {\n         alert (\'Kolom Lookup: \' + JSON.stringify(conf));\n     }\n \n     function generate_columns(e, dt, node, conf) {\n		let ids = dt.rows({ selected: true }).data().pluck(\'id\');		\n		if (ids.length == 0) 	return;\n		\n		console.log(ids);\n		\n		// add assoc key values, this will be posts values\n		var formData = new FormData();\n		$.each(ids, function (key, val) {\n			formData.append(\"data[\" +val+ \"]\", \"1\");\n		});\n		formData.append(\"action\", \"generate_columns\");\n\n		$.ajax({\n			type: \"POST\",\n			url: base_url +\"admin/api\",\n			async: true,\n			data: formData,\n			cache: false,\n			contentType: false,\n			processData: false,\n			timeout: 60000,\n			dataType: \'json\',\n			success: function(json) {\n				if (typeof json.error !== \'undefined\' && json.error != \"\" && json.error != null) {\n					alert(json.error);\n					return;\n				}\n\n				//reload dt but keep the paging\n				dt.ajax.reload( null, false );\n			},\n			error: function(jqXHR, textStatus, errorThrown) {\n				alert(textStatus);\n				return;\n			}\n		});\n    }\n\n </script>' WHERE (`id` = '8');

INSERT INTO `dbo_crud_custom_actions` (`table_id`, `label`, `order_no`, `css`, `onclick_js`, `selected`) VALUES ('8', 'Perbaharui Daftar Kolom', '1', 'btn-info', 'generate_columns', '2');

UPDATE `dbo_crud_columns` SET `data_priority` = '10' WHERE (`id` = '73');
UPDATE `dbo_crud_columns` SET `data_priority` = '11' WHERE (`id` = '70');
UPDATE `dbo_crud_columns` SET `order_no` = '4' WHERE (`id` = '73');
UPDATE `dbo_crud_columns` SET `edit_bubble` = '1' WHERE (`id` = '73');
UPDATE `dbo_crud_columns` SET `visible` = '0' WHERE (`id` = '68');
UPDATE `dbo_crud_columns` SET `visible` = '0' WHERE (`id` = '132');
UPDATE `dbo_crud_columns` SET `visible` = '0' WHERE (`id` = '140');
UPDATE `dbo_crud_columns` SET `data_priority` = '-1' WHERE (`id` = '70');

ALTER TABLE `dbo_crud_pages` 
ADD COLUMN `is_public` SMALLINT(6) NOT NULL DEFAULT 0 AFTER `page_size`;

INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`) VALUES (47, 'workflow', '46', 'Konfigurasi Workflow', 'table');
INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`) VALUES (48, 'workflow_instance', '52', 'Workflow', 'table');

INSERT INTO `dbo_crud_pages_subtables` (`page_id`, `subtable_id`, `label`, `table_key_column`, `subtable_fkey_column`, `page_size`, `order_no`) VALUES ('47', '47', 'Langkah', 'id', 'workflow_id', '10', '1');
INSERT INTO `dbo_crud_pages_subtables` (`page_id`, `subtable_id`, `label`, `table_key_column`, `subtable_fkey_column`, `page_size`, `order_no`) VALUES ('47', '49', 'Transisi', 'id', 'workflow_id', '10', '2');
INSERT INTO `dbo_crud_pages_subtables` (`page_id`, `subtable_id`, `label`, `table_key_column`, `subtable_fkey_column`, `page_size`, `order_no`) VALUES ('47', '51', 'Grup Pengguna', 'id', 'workflow_id', '10', '3');
INSERT INTO `dbo_crud_pages_subtables` (`page_id`, `subtable_id`, `label`, `table_key_column`, `subtable_fkey_column`, `page_size`, `order_no`) VALUES ('48', '53', 'Langkah', 'id', 'instance_id', '10', '1');
INSERT INTO `dbo_crud_pages_subtables` (`page_id`, `subtable_id`, `label`, `table_key_column`, `subtable_fkey_column`, `page_size`, `order_no`) VALUES ('48', '54', 'Tindakan', 'id', 'instance_id', '10', '2');

INSERT INTO `dbo_crud_permissions` (`role_id`, `page_id`) VALUES ('3', '48');

INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`, `ajax`, `initial_load`, `row_id_column`, `row_select_column`, `editor`, `allow_add`, `allow_edit`, `allow_delete`, `edit_row_action`, `delete_row_action`, `allow_export`, `allow_import`, `filter`, `soft_delete`, `data_model`, `limit_selection`, `page_size`, `created_on`, `updated_on`, `is_deleted`) VALUES ('55', 'Workflow Instances OPD', 'dbo_wf_instances', 'id', 'entity', '', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1', '1', 'opd/Mworkflows', '0', '25', '2021-04-17 12:14:50', '2021-04-17 12:14:50', '0');
UPDATE `dbo_crud_tables` SET `allow_add` = '0', `allow_edit` = '0', `allow_delete` = '0' WHERE (`id` = '52');
UPDATE `dbo_crud_tables` SET `allow_add` = '0', `allow_edit` = '0', `allow_delete` = '0' WHERE (`id` = '53');
UPDATE `dbo_crud_tables` SET `allow_add` = '0', `allow_edit` = '0', `allow_delete` = '0' WHERE (`id` = '54');

INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`) VALUES ('49', 'workflow_instance_opd', '55', 'Workflow OPD', 'table');

INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`) VALUES ('50', 'workflow_steps', '47', 'Konfigurasi Workflow - Langkah', 'table');
INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`) VALUES ('51', 'workflow_transitions', '49', 'Konfigurasi Workflow - Transisi', 'table');

INSERT INTO `dbo_crud_permissions` (`id`, `role_id`, `page_id`) VALUES ('36', '3', '50');
INSERT INTO `dbo_crud_permissions` (`id`, `role_id`, `page_id`) VALUES ('37', '3', '51');
UPDATE `dbo_crud_permissions` SET `allow_add` = '0', `allow_edit` = '0', `allow_delete` = '0', `no_access` = '0' WHERE (`id` = '35');

INSERT INTO `dbo_crud_permissions` (`role_id`, `page_id`, `allow_view`, `allow_add`, `allow_edit`, `allow_delete`, `no_access`) VALUES ('4', '49', '1', '0', '0', '0', '0');
UPDATE `dbo_crud_permissions` SET `no_access` = '0' WHERE (`id` = '36');
UPDATE `dbo_crud_permissions` SET `no_access` = '0' WHERE (`id` = '37');

UPDATE `dbo_crud_navigations` SET `is_deleted` = '1' WHERE (`id` = '38');
INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'Workflow', '', 'title', '', '0', '', '21', '2021-03-18 01:47:43', '2021-03-19 12:21:11', '990', '0');
INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'Konfigurasi', 'dripicons-gear', 'item', 'page', '47', '', '22', '2021-03-18 01:47:43', '2021-03-19 12:18:23', '990', '0');
INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'Workflow', 'dripicons-network-2', 'item', 'page', '48', '', '23', '2021-03-18 01:47:43', '2021-03-19 12:20:20', '990', '0');
INSERT INTO `dbo_crud_navigations` (`role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('3', 'Workflow', 'dripicons-network-2', 'item', 'page', '48', '', '23', '2021-03-18 01:47:43', '2021-03-19 12:20:20', '990', '0');
INSERT INTO `dbo_crud_navigations` (`role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES ('4', 'Workflow', 'dripicons-network-2', 'item', 'page', '49', '', '23', '2021-03-18 01:47:43', '2021-03-19 12:20:20', '990', '0');

INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`, `row_id_column`, `editor`, `allow_add`, `allow_edit`, `allow_delete`) VALUES ('56', 'SMS Inbox', 'dbo_sms_inbox', 'id', 'sender', '0', '0', '0', '0', '0');
INSERT INTO `dbo_crud_tables` (`id`, `name`, `table_name`, `key_column`, `lookup_column`, `row_id_column`, `editor`, `allow_add`, `allow_edit`, `allow_delete`) VALUES ('57', 'SMS Outbox', 'dbo_sms_outbox', 'id', 'recipient', '0', '0', '0', '0', '0');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '46');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '47');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '48');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '49');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '50');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '51');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '52');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '53');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '54');
UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '55');

INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`, `is_public`, `created_on`, `updated_on`, `is_deleted`) VALUES ('52', 'sms_inbox', '56', 'SMS Inbox', 'table', '0', '2021-04-18 10:49:44', '2021-04-18 10:49:44', '0');
INSERT INTO `dbo_crud_pages` (`id`, `name`, `crud_table_id`, `page_title`, `page_type`, `is_public`, `created_on`, `updated_on`, `is_deleted`) VALUES ('53', 'sms_outbox', '57', 'SMS Outbox', 'table', '0', '2021-04-18 10:49:44', '2021-04-18 10:49:44', '0');

INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'SMS', 'dripicons-device-mobile', 'item', 'dropdown', '0', '', '25', '2021-03-18 01:47:43', '2021-03-19 12:21:11', '990', '0');
INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'Inbox', '', 'subitem', 'page', '52', '', '26', '2021-03-18 01:47:43', '2021-03-19 12:18:23', '990', '0');
INSERT INTO `dbo_crud_navigations` (`id`, `role_id`, `label`, `icon`, `nav_type`, `action_type`, `page_id`, `url`, `order_no`, `created_on`, `updated_on`, `updated_by`, `is_deleted`) VALUES (NULL, '2', 'Outbox', '', 'subitem', 'page', '53', '', '27', '2021-03-18 01:47:43', '2021-03-19 12:20:20', '990', '0');
UPDATE `dbo_crud_navigations` SET `icon` = 'dripicons-network-2', `nav_type` = 'item', `action_type` = 'dropdown' WHERE (`id` = '81');
UPDATE `dbo_crud_navigations` SET `icon` = '', `nav_type` = 'subitem' WHERE (`id` = '82');
UPDATE `dbo_crud_navigations` SET `icon` = '', `nav_type` = 'subitem' WHERE (`id` = '83');

UPDATE `dbo_crud_tables` SET `row_id_column` = '0' WHERE (`id` = '45');

UPDATE `dbo_crud_navigations` SET `icon` = 'dripicons-help' WHERE (`id` = '62');
UPDATE `dbo_crud_navigations` SET `icon` = 'dripicons-help' WHERE (`id` = '64');
UPDATE `dbo_crud_navigations` SET `icon` = 'dripicons-help' WHERE (`id` = '78');

